[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/type/:slug"
  to = "/type/:slug/index.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/"
  status = 301

[[redirects]]
  from = "/result"
  to = "/result/index.html"
  status = 200
