import fs from 'node:fs';import assert from 'node:assert/strict';import {calculateDayMaster,today} from './src/daymaster.mjs';import {home,result,detail} from './src/render-v5.mjs';
const profiles=JSON.parse(fs.readFileSync(new URL('./src/profiles.json',import.meta.url)));const readings=JSON.parse(fs.readFileSync(new URL('./src/readings.json',import.meta.url)));const strip=s=>s.replace(/<[^>]+>/g,'').replace(/\s+/g,'');
assert.equal(profiles.length,10);assert.equal(new Set(profiles.map(p=>p.id)).size,10);
let textChecks=0;for(const p of profiles){const page=detail(p,readings),r=result(p,readings,profiles);assert(!page.includes('/test'));assert(!r.includes('/test'));for(const key of ['essence','firstImpression','innerWorld','thinkingDeep','emotionDeep','intimacyDeep','socialDeep','workDeep','underStress','blindSpot']){assert(strip(page).includes(strip(p.deep[key])),p.id+' '+key);assert(strip(r).includes(strip(p.deep[key])),p.id+' result '+key);textChecks++}for(const c of p.deep.compatibility){for(const key of ['why','watch','tip'])if(c[key]){assert(strip(page).includes(strip(c[key])));textChecks++}}const sections=[...page.matchAll(/data-section="([^"]+)"/g)].map(x=>x[1]);assert.equal(sections.length,new Set(sections).size,p.id+' duplicate sections')}
const html=home(profiles);const wheel=html.match(/<div class="wheel-center">([\s\S]*?)<\/div>/)[1];assert(wheel.includes('五行'));assert(!/丁火|点亮者|我的日主|04 \/ 10/.test(wheel));assert.equal((html.match(/aria-pressed="false"/g)||[]).length,5);assert(!html.includes('aria-pressed="true"'));assert(!html.includes('/test'));assert(!html.includes('现在开始'));assert(!html.includes('home-cta'));assert(html.includes('>出生日期<span>公历</span>'));
for(const p of profiles){const r=result(p,readings);assert(!r.includes('result-map'));assert(!r.includes('data-copy'));assert(!r.includes('五行系统'));assert(r.includes('href="/">回到首页'));}
assert(!fs.existsSync(new URL('./dist/test/index.html',import.meta.url)));
assert.equal(calculateDayMaster('2000-01-01').dayMaster,'戊');assert.equal(calculateDayMaster('2000-01-02').dayMaster,'己');assert.equal(calculateDayMaster('2000-01-03').dayMaster,'庚');assert.equal(calculateDayMaster('1949-10-01').dayMaster,'甲');for(const d of ['2001-02-29','1900-02-29','2026-13-01','2026-02-30','x'])assert.throws(()=>calculateDayMaster(d));assert.doesNotThrow(()=>calculateDayMaster('2000-02-29'));const all=new Set;for(let d=1;d<=10;d++)all.add(calculateDayMaster('2000-01-'+String(d).padStart(2,'0')).dayMaster);assert.equal(all.size,10);
const css=fs.readFileSync(new URL('./public/styles.css',import.meta.url),'utf8');assert(!/!important|brightness\(|contrast\(|mix-blend-mode|min-height:\s*[3-9]\d\dpx/.test(css));const client=fs.readFileSync(new URL('./public/app.js',import.meta.url),'utf8');assert(!/MutationObserver|hydrateRoot|vinext|RSC/.test(client));
console.log(JSON.stringify({profiles:10,textChecks,uniqueResultStems:all.size,homeNeutral:true,oneRenderPerSection:true,legacyRenderAndFiltersRemoved:true},null,2));
